In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers

# Define the 5x5 input matrix (you can modify these values as needed)
input_matrix = np.array([[1, 2, 3, 4, 5],
                         [6, 7, 8, 9, 10],
                         [11, 12, 13, 14, 15],
                         [16, 17, 18, 19, 20],
                         [21, 22, 23, 24, 25]], dtype=np.float32)

# Reshape input to match TensorFlow's expected shape: (batch, height, width, channels)
input_tensor = input_matrix.reshape((1, 5, 5, 1))

# Define the 3x3 kernel
kernel = np.array([[1, 0, -1],
                   [1, 0, -1],
                   [1, 0, -1]], dtype=np.float32)

# Reshape kernel to match TF shape: (kernel_height, kernel_width, input_channels, output_channels)
kernel_tensor = kernel.reshape((3, 3, 1, 1))

# Function to perform convolution given stride and padding
def perform_convolution(stride, padding):
    # Create a TensorFlow constant for the input and kernel
    inp = tf.constant(input_tensor)
    ker = tf.constant(kernel_tensor)

    # Use tf.nn.conv2d to perform the convolution
    conv_out = tf.nn.conv2d(inp, ker, strides=[1, stride, stride, 1], padding=padding)
    return conv_out.numpy().squeeze()  # Remove extra dimensions for printing

# Convolution cases
conv_valid_stride1 = perform_convolution(stride=1, padding='VALID')
conv_same_stride1 = perform_convolution(stride=1, padding='SAME')
conv_valid_stride2 = perform_convolution(stride=2, padding='VALID')
conv_same_stride2 = perform_convolution(stride=2, padding='SAME')

# Print the results
print("Output feature map (Stride = 1, Padding = 'VALID'):")
print(conv_valid_stride1)
print("\nOutput feature map (Stride = 1, Padding = 'SAME'):")
print(conv_same_stride1)
print("\nOutput feature map (Stride = 2, Padding = 'VALID'):")
print(conv_valid_stride2)
print("\nOutput feature map (Stride = 2, Padding = 'SAME'):")
print(conv_same_stride2)


Output feature map (Stride = 1, Padding = 'VALID'):
[[-6. -6. -6.]
 [-6. -6. -6.]
 [-6. -6. -6.]]

Output feature map (Stride = 1, Padding = 'SAME'):
[[ -9.  -4.  -4.  -4.  13.]
 [-21.  -6.  -6.  -6.  27.]
 [-36.  -6.  -6.  -6.  42.]
 [-51.  -6.  -6.  -6.  57.]
 [-39.  -4.  -4.  -4.  43.]]

Output feature map (Stride = 2, Padding = 'VALID'):
[[-6. -6.]
 [-6. -6.]]

Output feature map (Stride = 2, Padding = 'SAME'):
[[ -9.  -4.  13.]
 [-36.  -6.  42.]
 [-39.  -4.  43.]]
